### ISSUE TITLE
Neatline view breaks between pulling latest version and running upgrade

### ISSUE THREAD

**Issue by mkobayashi21** [performant-software/neatline-omeka-s#36] opened 2018-07-19 15:03 UTC
**What happened**
Noticing that there was an update on Github, I pulled the latest version of the code, and immediately tried to go to the Neatline view without updating. But all that showed was: 
```
Zend\Permissions\Acl\Exception\InvalidArgumentException
Resource 'Omeka\Controller\Site\Neatline' not found
Details:

exception 'Zend\Permissions\Acl\Exception\InvalidArgumentException' with message 'Resource 'Omeka\Controller\Site\Neatline' not found' in C:\wamp64\www\omeka-s\vendor\zendframework\zend-permissions-acl\src\Acl.php:291
Stack trace:
0 C:\wamp64\www\omeka-s\vendor\zendframework\zend-permissions-acl\src\Acl.php(731): Zend\Permissions\Acl\Acl->getResource('Omeka\\Controlle...')
1 C:\wamp64\www\omeka-s\application\src\Permissions\Acl.php(92): Zend\Permissions\Acl\Acl->isAllowed(Object(Omeka\Entity\User), 'Omeka\\Controlle...', 'browse')
2 C:\wamp64\www\omeka-s\application\src\Mvc\MvcListeners.php(430): Omeka\Permissions\Acl->userIsAllowed('Omeka\\Controlle...', 'browse')
3 C:\wamp64\www\omeka-s\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Omeka\Mvc\MvcListeners->authorizeUserAgainstController(Object(Zend\Mvc\MvcEvent))
4 C:\wamp64\www\omeka-s\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
5 C:\wamp64\www\omeka-s\vendor\zendframework\zend-mvc\src\Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
6 C:\wamp64\www\omeka-s\index.php(21): Zend\Mvc\Application->run()
7 {main}
```

The rest of the omeka-s continued working, but any Neatline view with "/neatline" gave the message above. 

**To fix**
All that was necessary to fix was to go to modules in omeka-s, and click update next to Neatline.

Additional comments by @akstuhl: 
> The Upgrade button is a standard part of how Omeka modules add fields to their database tables - so the note in the PR was to make sure anyone testing for the presence of those new fields knew to click Upgrade first, otherwise they wouldn’t see them. However, an end user who replaces their copy of the module with the latest version would reasonably expect the module to continue working between when they did that and when they ran the upgrade.

**Comment by akstuhl** [comment] 2018-07-20 16:43
After some further investigation, I think this may be more an Omeka issue than I assumed, rather than fully specific to Neatline.
- The bug can be reproduced by incrementing the version number in config/module.ini, even if no other changes have been introduced. So even if running Upgrade would be a no-op other than catching up Omeka's database-stored version number for the module to the number in module.ini, the module is disabled until Upgrade has been run.
- This same behavior can be reproduced for at least one other Omeka S module, CSVImport, again just be incrementing the version number in that module's config/module.ini file.
- An important difference between Neatline and CSVImport is that, since access to all views/routes is through the module's additions to the admin navigation tree in the latter's case, the user will no longer see links to CSVImport views if an upgrade is needed (thus making it more identifiable that they should go run the upgrade). For Neatline, end users will be navigating directly to the exhibit URLs and would be met with the error shown above. So the module would ideally have some way of detecting that an upgrade needs to be run and displaying that to an admin user / displaying some kind of maintenance notice to non-admin users.
- It would be useful to investigate further whether other modules have implemented upgrade-needed detection or if changes are in the works to Omeka S related to that scenario.

**Comment by akstuhl** [comment] 2019-05-11 17:47
Pulling the actual feature requirement out the above comment's thicket:

The Neatline for Omeka S module should have some way of detecting that an upgrade needs to be run and displaying that to an admin user / displaying some kind of maintenance notice to non-admin users.

**Comment by akstuhl** [comment] 2019-06-01 22:18
Unfortunately there seems to be very little that can be done about this from the Neatline side, as Omeka S will not load or execute any resources from a module whose version number in config/module.ini has changed. Moving this issue to a later milestone but keeping it open, as it would be good to keep track of any related changes in Omeka S and reassess the possibility.

**Closed as completed** 2021-02-24 19:57 UTC
Labels: bug
